[package]
	authors = ["Ian Pratt <ianjdpratt@gmail.com>"]
	edition = "2021"
	name    = "hematite"
	version = "0.2.1"

	description = "A Battlesnake written in Rust"
	keywords    = ["battlesnake"]
	readme      = "README.md"

[dependencies]
	env_logger = "0.9.0"
	itertools  = "0.10.5"
	log        = "0.4.0"
	rand       = { version = "0.8.5", features = ["alloc", "small_rng"] }
	rocket     = { version = "0.5.0-rc.1", features = ["json"] }
	serde      = { version = "1.0.117", features = ["derive"] }
	serde_json = "1.0.59"
