app          = "hematite"
kill_signal  = "SIGTERM"
kill_timeout = 5
processes    = []

[env]

[experimental]
	auto_rollback = true

[[services]]
	internal_port = 8080
	processes     = ["app"]
	protocol      = "tcp"
	script_checks = []

	[services.concurrency]
		hard_limit = 25
		soft_limit = 20
		type       = "connections"

	[[services.ports]]
		force_https = true
		handlers    = ["http"]
		port        = 80

	[[services.ports]]
		handlers = ["http", "tls"]
		port     = 443

	[[services.http_checks]]
		grace_period    = "5s"
		interval        = "5s"
		method          = "get"
		path            = "/"
		protocol        = "http"
		restart_limit   = 3
		timeout         = "500ms"
		tls_skip_verify = false
